select distinct ?concept ?property ?value
where {
	?resource soda:hasInferredContext ?context .
	FILTER (strends(str(?resource), ?var)).
	?context tosca:properties ?concept .
	?concept DUL:classifies ?property .
	OPTIONAL {?concept tosca:hasValue ?value .} 
	
	FILTER NOT EXISTS {
			?resource soda:hasInferredContext ?context2 .
			FILTER(?context != ?context2).
			?context2 tosca:properties ?classifier2.
			?classifier2 DUL:classifies ?property .
			
			?resource2 soda:hasContext ?context2 .
			#FILTER(?resource != ?resource2).	
			FILTER(?resource2 != owl:Nothing).
			?resource2 rdfs:subClassOf ?resource.	
	}
}


                