select ?resource ?capability ?optimizations ?templateType
where {
		{
			#capabilities of host nodes
			?resource (soda:hasContext/tosca:requirements/tosca:hasObjectValue)+/soda:hasContext/tosca:capabilities  ?capability .
		} UNION {	
			#direct capabilities
			?resource soda:hasContext/tosca:capabilities  ?capability .
		}
		?resource soda:hasContext/tosca:optimization ?optimizations .
		?resource sesame:directType ?templateType .
		?templateType rdfs:subClassOf tosca:tosca.entity.Root .
				
		?var_aadm soda:includesTemplate ?resource .
		#FILTER (contains(str(?aadm), ?var_aadm_id)).
	}
