select ?concept ?property ?resource
FROM sesame:nil
where {
	?resource soda:hasContext ?context .
	?resource rdfs:subClassOf tosca:tosca.interfaces.Root.
	?context tosca:operations ?concept .
	?concept DUL:classifies ?property .
}