---
- hosts: all
  become_user: root
  become: yes

  vars:
    pip_install_packages:
      - name: cryptography

  tasks:
    - set_fact:
        alt_name: "IP:{{ public_ipv4_address }}"
      when: public_ipv4_address != "localhost"
    - set_fact:
        alt_name: "URI:{{ public_ipv4_address }}"
      when: public_ipv4_address == "localhost"

    - name: Create certs and storage folders
      block:
        - file:
            path: "{{ cert_path }}"
            state: directory

    - name: Copy root CA files
      block:
        - copy:
            src: ca.crt
            dest: "{{ cert_path }}/ca.crt"
        - copy:
            src: ca.key
            dest: "{{ cert_path }}/ca.key"

    - name: Install root CA
      block:
        - command: "cp {{ cert_path }}/ca.crt /etc/pki/ca-trust/source/anchors/ca.crt"
        - command: update-ca-trust
      when: ansible_distribution == "CentOS"  

    - name: Install root CA
      block:
        - file:
            path: "/usr/local/share/ca-certificates/opera"
            state: directory
        - command: "cp {{ cert_path }}/ca.crt /usr/local/share/ca-certificates/opera/ca.crt"
        - command: update-ca-certificates
      when: ansible_distribution == "Ubuntu"        

    - name: Generate certificates and clean up
      block:
        - openssl_privatekey:
            path: "{{ cert_path }}/{{ cert_files_prefix }}.key"
            size: 4096
        - openssl_csr:
            path: "{{ cert_path }}/{{ cert_files_prefix}}.csr"
            privatekey_path: "{{ cert_path }}/{{ cert_files_prefix}}.key"
            country_name: "{{ country_name }}"
            organization_name: "{{ organization_name }}"
            email_address:  "{{ email_address }}"
            common_name: "{{ cert_files_prefix}}"
            subject_alt_name: "{{ alt_name }}"
        - openssl_certificate:
            path: "{{ cert_path }}/{{ cert_files_prefix}}.crt"
            csr_path: "{{ cert_path }}/{{ cert_files_prefix}}.csr"
            ownca_path: "{{ cert_path }}/ca.crt"
            ownca_privatekey_path: "{{ cert_path }}/ca.key"
            provider: "ownca"
        - file:
            state: absent
            path: "{{ cert_path }}/{{ cert_files_prefix}}.csr"

    - name: Install certificates for communication with the registry
      block:
        - file:
            path: "/etc/docker/certs.d/{{ registry_ip }}"
            state: directory
        - command: "cp {{ cert_path }}/ca.crt /etc/docker/certs.d/{{ registry_ip }}"
        - command: "cp {{ cert_path }}/{{ cert_files_prefix}}.key /etc/docker/certs.d/{{ registry_ip }}"
        - command: "cp {{ cert_path }}/{{ cert_files_prefix}}.crt /etc/docker/certs.d/{{ registry_ip }}/{{ cert_files_prefix}}.cert"

  roles:
    - role: geerlingguy.pip