SELECT distinct ?m ?time ?user ?dsl ?name ?isAADM ?namespace ?description ?version {
		?m a ?modelType .
        FILTER (?modelType  IN (soda:AbstractApplicationDeployment, soda:ResourceModel))  .
        FILTER (STRSTARTS(str(?m), ?aadm)) .
		?m soda:createdAt ?time .
		?m soda:createdBy ?user .
		?m soda:hasDSL ?dsl .
		?m soda:hasName ?name .
		BIND (xsd:boolean(exists{?m a soda:AbstractApplicationDeployment}) AS ?isAADM)
		
		?m DUL:isSettingFor ?resource .
        ?m soda:hasNamespace ?namespace .
		OPTIONAL {?m owl:versionInfo ?version .}
		OPTIONAL {?m dcterms:description ?description .}
} order by ?m ?time ?user ?dsl ?name ?isAADM ?namespace  ?description ?version