SELECT ?m ?time ?user ?dsl ?name ?version {
		?m a soda:AbstractApplicationDeployment .
		?m soda:createdAt ?time .
		?m soda:createdBy ?user .
		?m soda:hasDSL ?dsl .
		?m soda:hasName ?name .
		
		?m DUL:isSettingFor ?n .
        
		FILTER NOT EXISTS
		{ 
			GRAPH ?g { ?n ?p ?o } 
		}
    
		?n soda:hasContext ?c
		OPTIONAL {?m owl:versionInfo ?version .} 
} group by ?m ?time ?user ?dsl ?name ?version
