SELECT ?m ?time ?user ?dsl ?name ?description {
		?m a soda:ResourceModel .
		?m soda:createdAt ?time .
		?m soda:createdBy ?user .
		?m soda:hasDSL ?dsl .
		?m soda:hasName ?name .
		
		?m DUL:isSettingFor ?n .
        
		FILTER NOT EXISTS
		{ 
			GRAPH ?g { ?n ?p ?o } 
		}
    
		?n soda:hasContext ?c .
		OPTIONAL {?m dcterms:description ?description .}
} group by ?m ?time ?user ?dsl ?name ?description
