SELECT ?m ?time ?user ?dsl ?name ?isAADM ?version {
		?m a ?modelType .
		FILTER (?modelType  IN (soda:AbstractApplicationDeployment, soda:ResourceModel)) 
		?m soda:createdAt ?time .
		?m soda:createdBy ?user .
		?m soda:hasDSL ?dsl .
		?m soda:hasName ?name .
        
		?m DUL:isSettingFor ?n .
		BIND (xsd:boolean(exists{?m a soda:AbstractApplicationDeployment}) AS ?isAADM)
        
		GRAPH ?g {
			?n soda:hasContext ?c .
			?n soda:hasName ?res_name
		}
		
		OPTIONAL {?m owl:versionInfo ?version .} 
    	
}