select distinct ?optimization
where {
    ?concept rdf:type opt:OptimConcept 
	FILTER (strends(lcase(str(?concept)), ?var_1))
	?concept opt:hasCapability ?g .
	?g rdf:type opt:GPU .
	?g opt:hasValue_greater_or_equal ?num_gpus .
	FILTER ((xsd:integer(?var_2)) >= ?num_gpus)
	?g opt:hasOptimization ?optimization .
}
