select ?template  ?v  ?r_a ?r_i
where {
	?aadm soda:includesTemplate ?template .
    
	?template a soda:SodaliteSituation ;
            sesame:directType ?templateType .
	?templateType soda:hasInferredContext ?ctx.
	?templateType rdfs:subClassOf tosca:tosca.entity.Root. 
	?ctx tosca:requirements ?r .
	?r DUL:classifies ?r_a.
	?r DUL:hasParameter [DUL:classifies ?r_i; DUL:hasRegion ?v] .
	?r DUL:hasParameter [DUL:classifies tosca:occurrences; DUL:hasParameter [DUL:classifies tosca:min; tosca:hasDataValue ?occMin]] .
	FILTER (xsd:integer(?occMin) > 0) .
	FILTER NOT EXISTS {
		?template soda:hasContext [tosca:requirements [DUL:classifies ?r_a]] .
    }
}
