# template, r_a, ctx
select *
where {
    ?template soda:hasContext [tosca:requirements [DUL:classifies ?r_a; DUL:hasParameter [DUL:classifies tosca:relationship; DUL:hasParameter [DUL:classifies tosca:type; DUL:hasRegion ?templateRelationshipType]]]] .
	?ctx tosca:requirements [DUL:classifies ?r_a; DUL:hasParameter [DUL:classifies tosca:relationship; DUL:hasParameter [DUL:classifies tosca:type; DUL:hasRegion ?r_d_relationship]]] .
	FILTER NOT EXISTS {?templateRelationshipType rdfs:subClassOf ?r_d_relationship .}
}