select ?aadm ?createdAt ?user ?namespace (group_concat(distinct concat(str(?template), "|" , str(?superclass))) as ?templates) (group_concat(distinct concat(str(?input), "|" , str(?superclass2))) as ?inputs) (group_concat(distinct concat(str(?output), "|" , str(?superclass3))) as ?outputs)
where {
	?aadm soda:createdAt ?createdAt .
	?aadm soda:createdBy ?user .
	?aadm soda:hasNamespace ?namespace .
	?aadm soda:includesTemplate ?template .
	OPTIONAL {?aadm soda:includesInput ?input . ?input sesame:directType ?superclass2 . ?superclass2 rdfs:subClassOf soda:SodaliteSituation}
	OPTIONAL {?aadm soda:includesOutput ?output . ?output sesame:directType ?superclass3. ?superclass3 rdfs:subClassOf soda:SodaliteSituation}
    ?template sesame:directType ?superclass .
    ?superclass rdfs:subClassOf soda:SodaliteSituation .
} group by ?aadm ?createdAt ?user ?namespace