SELECT ?node ?description ?superclass ?g 
WHERE {
	?node a tosca:tosca.nodes.Root .
	?node a ?var .   
	?node sesame:directType ?superclass .
	?superclass rdfs:subClassOf tosca:tosca.nodes.Root . 
	?node soda:hasContext ?c .
	OPTIONAL {?node dcterms:description ?description .} 
        
	FILTER NOT EXISTS
	{
		GRAPH ?g { ?node soda:hasContext ?c . } 
	}
}