select distinct ?concept ?property ?value
where {
	?resource soda:hasContext ?context .
	FILTER (strends(str(?resource), ?var)).
	?context tosca:input ?concept .
	?concept DUL:classifies ?property .
	OPTIONAL {?concept tosca:hasValue ?value .} 	
}


                