select distinct ?concept ?property ?resource
where {
	?resource soda:hasInferredContext ?context .
	#FILTER (strends(str(?resource), ?var)).
	?context tosca:operations ?concept .
	?concept DUL:classifies ?property .
}


                
