select distinct ?concept ?property
where {
	?resource soda:hasContext ?context .
	#FILTER (strends(str(?resource), ?var)).
	?context tosca:operations ?concept .
	?concept DUL:classifies ?property .
}


                
