select distinct ?concept ?property ?value  ?description
where {
	?resource soda:hasContext ?context .
	#FILTER (strends(str(?resource), ?var)).
	?context tosca:output ?concept .
	?concept DUL:classifies ?property .
	OPTIONAL {?concept tosca:hasValue ?value .}
	OPTIONAL {?resource dcterms:description ?description .}	
}
