select distinct ?value 
where {
		?resource soda:hasInferredContext ?context .
		#FILTER (strends(str(?resource), ?var)).
		?context tosca:valid_target_types [tosca:hasValue [tosca:hasValue ?value]] .
		
}



                
